language: node_js
sudo: false

node_js:
  - 0.10

before_install:
  - bash ./bin/prepublish.sh

before_script:
  - bower install
  - node ./bin/protractor-fix-version.js

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate < ./coverage/**/lcov.info


deploy:
  provider: npm
  email: thaiat@ipelia.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: Yoobic/yoobic-angular-core
